SELECT * FROM Books;
SELECT * FROM Customers;
SELECT * FROM Orders;

                                     -- ADVANCED QUERIES:

-- 1) Retrieve the total number of books sold for each genre:
SELECT SUM(O.QUANTITY) AS TOTAL_BOOKS_SOLD, B.GENRE
FROM BOOKS B
JOIN ORDERS O
ON B.BOOK_ID = O.BOOK_ID
GROUP BY B.GENRE;


-- 2) Find the average price of books in the "Fantasy" genre:
SELECT AVG(PRICE) AS AVG_PRICE
FROM BOOKS
WHERE GENRE = 'Fantasy';


-- 3) List customers who have placed at least 2 orders:
SELECT O.CUSTOMER_ID, COUNT(O.ORDER_ID) AS COUNT_ORDERS, C.NAME
FROM ORDERS O
JOIN CUSTOMERS C 
ON O.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY O.CUSTOMER_ID, C.NAME
HAVING COUNT(O.ORDER_ID) >= 2
ORDER BY O.CUSTOMER_ID;


-- 4) Find the most frequently ordered book:
SELECT COUNT(O.ORDER_ID) AS ORDER_COUNT, O.BOOK_ID, B.TITLE
FROM ORDERS O
JOIN BOOKS B
ON O.BOOK_ID = B.BOOK_ID
GROUP BY O.BOOK_ID, B.TITLE
ORDER BY ORDER_COUNT DESC LIMIT 1;


-- 5) Show the top 3 most expensive books of 'Fantasy' Genre :
SELECT * FROM BOOKS
WHERE GENRE = 'Fantasy'
ORDER BY PRICE DESC LIMIT 3;


-- 6) Retrieve the total quantity of books sold by each author:
SELECT B.AUTHOR, SUM(O.QUANTITY) AS TOTAL_QUANTITY_SOLD
FROM BOOKS B
JOIN ORDERS O
ON B.BOOK_ID = O.BOOK_ID
GROUP BY B.AUTHOR;


-- 7) List the cities where customers who spent over $30 are located:
SELECT DISTINCT C.CITY, C.NAME, O.TOTAL_AMOUNT
FROM CUSTOMERS C
JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE O.TOTAL_AMOUNT > 30
ORDER BY O.TOTAL_AMOUNT;


-- 8) Find the customer who spent the most on orders:
SELECT C.CUSTOMER_ID, C.NAME, SUM(O.TOTAL_AMOUNT) AS TOTAL_SPENT
FROM CUSTOMERS C
JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY C.NAME, C.CUSTOMER_ID
ORDER BY TOTAL_SPENT DESC LIMIT 1;


--9) Calculate the stock remaining after fulfilling all orders:
SELECT B.BOOK_ID, B.TITLE, B.STOCK, COALESCE(SUM(O.QUANTITY),0) AS ORDER_QTY,
        B.STOCK - COALESCE(SUM(O.QUANTITY),0) AS REMAINING_STOCK
FROM BOOKS B
LEFT JOIN ORDERS O
ON B.BOOK_ID = O.BOOK_ID
GROUP BY B.BOOK_ID
ORDER BY B.BOOK_ID;
